export const CHILD_CATEGORY_LIST_REQUEST                      = "CHILD_CATEGORY_LIST_REQUEST";
export const CHILD_CATEGORY_LIST_SUCCESS                      = "CHILD_CATEGORY_LIST_SUCCESS";
export const CHILD_CATEGORY_LIST_FAIL                         = "CHILD_CATEGORY_LIST_FAIL";
export const CHILD_CATEGORY_LIST_RESET                        = "CHILD_CATEGORY_LIST_RESET";

export const CHILD_CATEGORY_STORE_REQUEST                     = "CHILD_CATEGORY_STORE_REQUEST";
export const CHILD_CATEGORY_STORE_SUCCESS                     = "CHILD_CATEGORY_STORE_SUCCESS";
export const CHILD_CATEGORY_STORE_FAIL                        = "CHILD_CATEGORY_STORE_FAIL";
export const CHILD_CATEGORY_STORE_RESET                       = "CHILD_CATEGORY_STORE_RESET";

export const CHILD_CATEGORY_UPDATE_REQUEST                    = "CHILD_CATEGORY_UPDATE_REQUEST";
export const CHILD_CATEGORY_UPDATE_SUCCESS                    = "CHILD_CATEGORY_UPDATE_SUCCESS";
export const CHILD_CATEGORY_UPDATE_FAIL                       = "CHILD_CATEGORY_UPDATE_FAIL";
export const CHILD_CATEGORY_UPDATE_RESET                      = "CHILD_CATEGORY_UPDATE_RESET";

export const CHILD_CATEGORY_SHOW_REQUEST                      = "CHILD_CATEGORY_SHOW_REQUEST";
export const CHILD_CATEGORY_SHOW_SUCCESS                      = "CHILD_CATEGORY_SHOW_SUCCESS";
export const CHILD_CATEGORY_SHOW_FAIL                         = "CHILD_CATEGORY_SHOW_FAIL";
export const CHILD_CATEGORY_SHOW_RESET                        = "CHILD_CATEGORY_SHOW_RESET";

export const CHILD_CATEGORY_DELETE_REQUEST                    = "CHILD_CATEGORY_DELETE_REQUEST";
export const CHILD_CATEGORY_DELETE_SUCCESS                    = "CHILD_CATEGORY_DELETE_SUCCESS";
export const CHILD_CATEGORY_DELETE_FAIL                       = "CHILD_CATEGORY_DELETE_FAIL";