export const PARENT_CATEGORY_LIST_REQUEST                      = "PARENT_CATEGORY_LIST_REQUEST";
export const PARENT_CATEGORY_LIST_SUCCESS                      = "PARENT_CATEGORY_LIST_SUCCESS";
export const PARENT_CATEGORY_LIST_FAIL                         = "PARENT_CATEGORY_LIST_FAIL";
export const PARENT_CATEGORY_LIST_RESET                        = "PARENT_CATEGORY_LIST_RESET";

export const PARENT_CATEGORY_STORE_REQUEST                     = "PARENT_CATEGORY_STORE_REQUEST";
export const PARENT_CATEGORY_STORE_SUCCESS                     = "PARENT_CATEGORY_STORE_SUCCESS";
export const PARENT_CATEGORY_STORE_FAIL                        = "PARENT_CATEGORY_STORE_FAIL";
export const PARENT_CATEGORY_STORE_RESET                       = "PARENT_CATEGORY_STORE_RESET";

export const PARENT_CATEGORY_UPDATE_REQUEST                    = "PARENT_CATEGORY_UPDATE_REQUEST";
export const PARENT_CATEGORY_UPDATE_SUCCESS                    = "PARENT_CATEGORY_UPDATE_SUCCESS";
export const PARENT_CATEGORY_UPDATE_FAIL                       = "PARENT_CATEGORY_UPDATE_FAIL";
export const PARENT_CATEGORY_UPDATE_RESET                      = "PARENT_CATEGORY_UPDATE_RESET";

export const PARENT_CATEGORY_SHOW_REQUEST                      = "PARENT_CATEGORY_SHOW_REQUEST";
export const PARENT_CATEGORY_SHOW_SUCCESS                      = "PARENT_CATEGORY_SHOW_SUCCESS";
export const PARENT_CATEGORY_SHOW_FAIL                         = "PARENT_CATEGORY_SHOW_FAIL";
export const PARENT_CATEGORY_SHOW_RESET                        = "PARENT_CATEGORY_SHOW_RESET";

export const PARENT_CATEGORY_DELETE_REQUEST                    = "PARENT_CATEGORY_DELETE_REQUEST";
export const PARENT_CATEGORY_DELETE_SUCCESS                    = "PARENT_CATEGORY_DELETE_SUCCESS";
export const PARENT_CATEGORY_DELETE_FAIL                       = "PARENT_CATEGORY_DELETE_FAIL";