
export const USER_LOGIN_REQUEST                     = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS                     = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL                        = "USER_LOGIN_FAIL";
export const USER_LOGOUT                            = "USER_LOGOUT";

export const USER_REGISTER_REQUEST                  = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS                  = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL                     = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET                    = "USER_REGISTER_RESET";

export const USER_FORGOT_PASSWORD_REQUEST           = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS           = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL              = "USER_FORGOT_PASSWORD_FAIL";

export const USER_RESET_PASSWORD_REQUEST            = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCCESS            = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAIL               = "USER_RESET_PASSWORD_FAIL";

export const USER_TOKEN_RESET_PASSWORD_REQUEST      = "USER_TOKEN_RESET_PASSWORD_REQUEST";
export const USER_TOKEN_RESET_PASSWORD_SUCCESS      = "USER_TOKEN_RESET_PASSWORD_SUCCESS";
export const USER_TOKEN_RESET_PASSWORD_FAIL         = "USER_TOKEN_RESET_PASSWORD_FAIL";

export const USER_UPDATE_CREDENTIALS_REQUEST        = "USER_UPDATE_CREDENTIALS_REQUEST";
export const USER_UPDATE_CREDENTIALS_SUCCESS        = "USER_UPDATE_CREDENTIALS_SUCCESS";
export const USER_UPDATE_CREDENTIALS_FAIL           = "USER_UPDATE_CREDENTIALS_FAIL";
export const USER_UPDATE_CREDENTIALS_RESET          = "USER_UPDATE_CREDENTIALS_RESET";